### ISSUE TITLE
Required SPDX identifiers for DCO?

### ISSUE THREAD

**Issue by evelikov** [fsfe/reuse-tool#1075]
Just recently I was mentioned about reuse, so please forgive me my ignorance :sweat_smile: 

A few projects that I hack* on use [DCO] and for the sake of clarity and transparency, a copy is included in the repo. At the same time, reuse-tool flags the file as lacking license.

Would it make sense for skip the file (based on name, contents, other) or alternatively what would your recommend on the topic.

Thanks in advance

[DCO]: https://developercertificate.org/

**Comment by carmenbianca** [comment]
Hi! This FAQ entry should hopefully answer your question: https://reuse.software/faq/#exclude-file

REUSE treats the DCO file like any other, and it's a design choice by REUSE to not allow any files to be ignored/skipped. The unfortunate thing you need to figure out now is:

- who is the copyright holder of the DCO blurb
- under what licence is the DCO blurb licensed

and add those to either `your_DCO_file.license` or to `REUSE.toml`.

… this is, of course, stupid licence-of-licence work. Fortunately, the DCO contains some info: Linux Foundation is the copyright holder, and the licence is:

> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

which you would need to put in `LICENSES/LicenseRef-DCO.txt`.

Alternatively, put the entire DCO file in `LICENSES/LicenseRef-DCO.txt` so that you needn't provide the copyright holder and licence of this file. However, in order to still comply with REUSE, you would need to have at least one file which is 'licensed' under `LicenseRef-DCO`. `CONTRIBUTING.md` is a good candidate for this.
