### ISSUE TITLE
Confusing mesage for reuse addheader --explicit-license in nonexisting folder

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-tool#140]
`reuse addheader --copyright="TEST" --license="TEST" --explicit-license "/tmp/nonexististngfolder/file.png"`

Gives
```
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE]
                       [--year YEAR]
                       [--style {c,css,haskell,html,ml,python,tex}]
                       [--template TEMPLATE] [--exclude-year]
                       [--explicit-license]
                       path [path ...]
reuse addheader: error: argument path: can't write to '/tmp/nonexististngfolder/file.png'
```

`can't write to "file"` is confusing where by `--explicit-license` reuse is requested to not work on the file directly.

**Comment by carmenbianca** [comment]
I'm afraid that this inconvenience isn't really possible for me to fix. The check to see whether it is possible to write to a file/directory exists long before the logic that turns `path` into `path.license`.

I could try to write in a special case, but I run into the issue where the logic that produces the read-write error does not have access to *any* context other than the argument it is given (the path). It does not know of any other context, and cannot know of any other context, certainly not a list of parsed arguments. I do not know how to pass it a list of parsed arguments, because it must itself be parsed before a list of parsed arguments could even exist.

So I doubt that this issue will ever be closed. Marking `wontfix` but keeping it open in case I get a flash of genius. Otherwise I'll close it after a while.

**Comment by mxmehl** [comment]
Closing as Carmen didn't get a flash of genius apparently :(
