### ISSUE TITLE
Comments in bibtex files?

### ISSUE THREAD

**Issue by lechten** [fsfe/reuse-tool#146]
Hi, many thanks for your continued work on this project!

I'm using the following as header in a [BibTeX file](https://gitlab.com/oer/oer.gitlab.io/blob/master/references.bib):

```
@Comment{SPDX-FileCopyrightText: 2017-2019 Jens Lechtenbörger}
@Comment{SPDX-License-Identifier: CC0-1.0}
```

On that file, `reuse lint` fails with:

```
reuse._util - ERROR - Could not parse 'CC0-1.0}'
reuse.project - ERROR - references.bib holds an SPDX expression that cannot be parsed, skipping the file
```

Why did the tool not fail on the previous line that also ends with `}`? Could you please accept the above syntax?

**Comment by carmenbianca** [comment]
Hi!

> Why did the tool not fail on the previous line that also ends with `}`?

Because the SPDX expression parser is a lot stricter than the copyright parser.

I've created #147 that should fix this issue. Can you please confirm for me whether the below is a valid BibTex comment?

```
@Comment{
Hello, world!
}
```

(Never mind if it's beautiful, but the primitive comment parser tool I wrote can't handle single-line comments that have a suffix. Oops.)

**Comment by lechten** [comment]
Yes, such comments work for me with biber and biblatex. Many thanks for the quick reply and fix!

**Comment by lechten** [comment]
I meant `biber` and `bibtex`...
