### ISSUE TITLE
REUSE badge not displayed on gitlab.com

### ISSUE THREAD

**Issue by lechten** [fsfe/reuse-tool#149]
Hi, I added the badge to the README of [emacs-reveal](https://gitlab.com/oer/emacs-reveal). However, instead of the badge, only the alt title is displayed after some delay. What might be the reason?

**Comment by carmenbianca** [comment]
I am not entirely sure, because it works when you go directly to <https://api.reuse.software/badge/gitlab.com/oer/emacs-reveal>. The website is also being generally quite slow. @mxmehl ?

test: ![badge](https://api.reuse.software/badge/gitlab.com/oer/emacs-reveal)

**Comment by mxmehl** [comment]
I see some pattern with gitlab.com. Badges for repos there need a long time to load (>4s), and I cannot say why exactly. This leds gitlab to the conclusion that the image cannot be loaded at all, probably because there is a timeout for the lazy loading. Also see https://api.reuse.software/info/gitlab.com/gitlab-org/gitlab

Badges for other repos load much faster for me, e.g.:
* https://api.reuse.software/badge/github.com/fsfe/reuse-tool
* https://api.reuse.software/badge/git.fsfe.org/fsfe/fsfe-website

I've created an issue in the API's repo: https://git.fsfe.org/reuse/api/issues/34

**Comment by mxmehl** [comment]
Closing this as it's not an issue of the tool

**Comment by mxmehl** [comment]
FYI, this issue has been fixed, the button is displayed now.

**Comment by lechten** [comment]
Great, many thanks!
