### ISSUE TITLE
Unneeded empty lines in license text for "reuse download LGPL-3.0-only"

### ISSUE THREAD

**Issue by cordlandwehr** [fsfe/reuse-tool#178]
When calling "reuse download LGPL-3.0-only" the LGPL-3.0-only license is correctly downloaded and placed into the LICENSES directory. Yet, in lines 22ff, 33ff, 47ff, each there are two additional unneeded empty lines that are not contained in the license statement on spdx.org: https://spdx.org/licenses/LGPL-3.0-only.html#licenseText

**Comment by carmenbianca** [comment]
Hi @cordlandwehr 

The text comes from here: https://github.com/spdx/license-list-data/blob/master/text/LGPL-3.0-or-later.txt

I'm afraid it's an issue in upstream.

Annoyingly, that text isn't the canonical version. I believe I had opened an issue at SPDX to request the canonical versions of licenses, but I can't find it at the moment. @mxmehl ?

**Comment by krop** [comment]
> Hi @cordlandwehr
> 
> The text comes from here: https://github.com/spdx/license-list-data/blob/master/text/LGPL-3.0-or-later.txt
> 
> I'm afraid it's an issue in upstream.
> 
> Annoyingly, that text isn't the canonical version. I believe I had opened an issue at SPDX to request the canonical versions of licenses, but I can't find it at the moment. @mxmehl ?

Likely this one https://github.com/spdx/license-list-data/issues/16

**Comment by cordlandwehr** [comment]
That upstream issue is tagged to have been fixed in the SPDX license list version 3.1 (now we are at 3.8). If nobody knows another upstream issue that tracks the current license problem, I can create a new upstream issue.

**Comment by mxmehl** [comment]
I am not aware of any other, so creating a new issue seems to be the best next step here. Thanks for flagging it!

**Comment by goneall** [comment]
Just posting an update here - the issue has been moved to the tool that generates the license-list-data: https://github.com/spdx/LicenseListPublisher/issues/61

**Comment by goneall** [comment]
I agree it would be very nice to maintain the canonical text.

I am willing to update the tool to use the canonical text in the license-list-data repo if there was a repository location where the undisputed canonical text could be found (e.g. a subdirectory in the LicenseList-XML rep).

The reason this hasn't been addressed previously is a lack of volunteer bandwidth to identify and maintain what would be considered the canonical text.  If we had enough volunteers to maintain the canonical text, we could propose a solution.  This could be raised on one of SPDX legal calls - I'm sure they would welcome the additional volunteer help to resolves this long standing issue.

I would recommend against opening an issue for this as it has been discussed and closed previously due to lack of volunteers to do the work.
