### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by alandtse** [fsfe/reuse-tool#185]
It'd be great if there was a [GitHub actions](https://help.github.com/en/actions) published by fsfe so we could just drop it in.

Yes, I know the instructions are [here](https://reuse.software/dev/).  But since there's a [marketplace ](https://github.com/marketplace?type=actions)for actions it'd be nice to just tell folks to select it from there.

**Comment by mxmehl** [comment]
Good idea, thank you! I will check it out. Found some documentation how to do it here: https://help.github.com/en/actions/building-actions/publishing-actions-in-github-marketplace

**Comment by mxmehl** [comment]
I have released a pre-release of a Github action for REUSE: https://github.com/marketplace/actions/reuse-compliance-check

I am not entirely happy with it because it only supports defining another subcommand (e.g. `spdx`), but not multiple arguments (like `--include-submodules` and `--debug`). This is because Github does not accept arrays for inputs. @carmenbianca, do you have a better idea?

**Comment by alandtse** [comment]
I haven't built an action before, but my understanding is you can set ENV variables to pass arguments? Is the issue that reuse doesn't support ENV variables?

**Comment by mxmehl** [comment]
I can provide an argument, but if the argument passed to the action contains multiple arguments (e.g. `--include-submodules lint`), the reuse tool fails to understand that. Not sure whether the tool could be made to understand that, or whether we have to improve the action.

I will close this issue here however since we're discussion that in the action's repo: https://github.com/fsfe/reuse-action/issues/3
