### ISSUE TITLE
[Question] How to run reuse lint on a file other than a path?

### ISSUE THREAD

**Issue by soimsoim** [fsfe/reuse-tool#193]
I want to run a reuse lint on a file that is not a path. 
Is there a way to do that?

This is because I want to analyze only files that have been committed in CI/CD environment.

**Comment by mxmehl** [comment]
AFAIK this is not possible. REUSE does not only check for license and copyright in a file, but considers the whole project, especially whether for every found license identifier the full license text is available. Since there is also the option to express licensing/copyright info in a central dep5 file, REUSE has to be aware of the whole project.

To see the status of a single file (as part of the full project), you would have to do some parsing of the `reuse lint` or the `reuse spdx` output. There is a plan to make that also available as JSON and/or YAML.

**Comment by carmenbianca** [comment]
@mxmehl is right. This tool used to be able to handle single files owing to legacy reasons (I *started* the tool as a means to check single files), but this feature was removed because REUSE is ultimately about projects/packages, not single files.

`reuse spdx` should do what you want, though. You'll need to do manual introspection. Failing that, try something like this script:

```python
from reuse import report, project

prj = project.Project(".")
path = "foo.py"
rep = report.FileReport.generate(prj, path)

assert not rep.bad_licenses
# assert not rep.missing_licenses

assert rep.spdxfile.licenses_in_file
assert rep.spdxfile.copyright
```

IMPORTANT: The above code is totally API-unstable. It might not work with any next version of reuse.

**Comment by soimsoim** [comment]
Thank you for your kind answers.
