### ISSUE TITLE
Add some relevant GitHub topics

### ISSUE THREAD

**Issue by dominiksalvet** [fsfe/reuse-tool#21]
Hello! Would it be possible to add some relevant GitHub topics to this repository? It would be great and also it might bring some people.

I also want to say '**Thank you**' this way for developing this project! :heart: I have been using it in my every single software project (and even in some non-software focused ones) I have developed using Git. Still remember when I found it on FSFE Git and it was exactly what I wanted. Just type `reuse lint` and that's all.

It's a shame that this project is so underestimated. Yet, it is one of my GitHub stars! :star:

**Comment by carmenbianca** [comment]
Thanks for the kind words Dominik :) I'll see about adding a few GitHub topics, though I'm not very familiar with the concept.

You may also like to be aware that the project is due to change quite a bit. You can find the proposed changes in https://github.com/fsfe/reuse-docs/pull/23 and https://github.com/fsfe/reuse-docs/pull/18. All projects that are currently compliant should remain compliant, though there are some additional tests (e.g., no unused licenses).

**Comment by dominiksalvet** [comment]
@carmenbianca Well, keep up the good work! :+1: Would you mind adding [`reuse`](https://github.com/topics/reuse) and [`analyzer`](https://github.com/topics/analyzer) topics as well? :smile:

**Comment by carmenbianca** [comment]
Done :)
