### ISSUE TITLE
Bad license when operator '+' is used

### ISSUE THREAD

**Issue by FedericoVaga** [fsfe/reuse-tool#275]
The command `reuse lint` reports the use of a BAD license when the '+' operator is used.

https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/#simple-license-expressions

From this page I understand that the '+' operator can be applied on any license in https://spdx.org/licenses/ (except the already marked _-or-later_). But despite this if I use it I get:

`* Bad licenses: CERN-OHL-W-2.0+`

**Comment by mxmehl** [comment]
True, `+` seems to be a valid SPDX expression. I wonder why we didn't support this from the start.

@silverhook, just for the sake of completeness: can you confirm that REUSE should support + expression except for the explicitely marked licenses which are supposed to use `-or-later`?

**Comment by silverhook** [comment]
I confirm that `+` is a valid SPDX expression, which according to the spec can be applied to any license ID.

The fact that the GPL family of licenses use the `-or-later` (and `-only`) suffixes, is an exception to the above, and is a result of a request of and subsequent long discussion with the FSF. If you are interested, [here is an incomplete summary into that](https://wiki.spdx.org/view/Legal_Team/or-later-vs-unclear-disambiguation). Prior to this change, you would also indicate `GPL-2.0+` instead of `GPL-2.0-or-later` – the former is still valid ID if you rely on an older SPDX Spec/Licese List.

The `reuse` tool should acknowledge the use of the `+`, yes.

**Comment by mxmehl** [comment]
Thanks for the confirmation, Matija!

**Comment by carmenbianca** [comment]
#314 should fix this.
