### ISSUE TITLE
Documentation: Explain how to "ignore" files/folders

### ISSUE THREAD

**Issue by arcturus140** [fsfe/reuse-tool#28]
From the documentation:

> If your project includes documentation which is not included in the final build
artefact, you are encouraged but not obliged to include license information for
these too.

Is it possible to specifically exclude folders or files from `reuse lint`?

**Comment by carmenbianca** [comment]
This isn't possible. These issues/PRs are related:

https://github.com/fsfe/reuse-docs/pull/23

https://github.com/fsfe/reuse-docs/pull/18

https://github.com/fsfe/reuse-docs/issues/14

The conclusion is that there are better ways to do this. But the documentation for these better ways doesn't exist yet for the current version of REUSE. I should probably document that within this tool as well.

**Comment by arcturus140** [comment]
Thank you for the insight. My conclusion from this is that I am probably inclined to work around the spec, and better advised adding license information for these files as well. 

I don't understand the use case for the section cited in my initial comment. The documentation is not in git ignore and therefore pushed to the repository. Yet, it is not distributed with the software and the documentation in the repository defaults to full copyright. 

Is this correct?

**Comment by carmenbianca** [comment]
> Yet, it is not distributed with the software and the documentation in the repository defaults to full copyright.

If you don't clearly say that "the documentation is under so-and-so license", then it _probably_ defaults to copyright.

If you want the documentation to be under a free license, you can add license headers as you would normally add to code. Alternatively, you can use the `debian/copyright` file to mark an entire directory as being under a certain license. See [this file] for reference:

```
Files: docs/*.rst
Copyright: 2017-2018 Free Software Foundation Europe e.V.
License: CC-BY-SA-4.0
```

If you do not want to freely license the documentation, then you could simply leave it as-is. The linter will complain in that scenario, however, which is annoying. One way to fix that is by adding the file `LICENSES/LicenseRef-Proprietary.txt` to your project, adding something like "All rights reserved" as the body text, and marking the documentation files with `SPDX-License-Identifier: LicenseRef-Proprietary`.

The reason files cannot be ignored is because one goal of the project is clarity. Ignoring files doesn't really improve clarity at all.

**Comment by carmenbianca** [comment]
Ah, sorry, was supposed to link this file in the previous comment:

https://github.com/fsfe/reuse-tool/blob/master/.reuse/dep5

**Comment by mxmehl** [comment]
Seems to be resolved. [fsfe/reuse-docs](https://github.com/fsfe/reuse-docs) now contains the tutorial and FAQ which explain the different options. Please leave feedback in the reuse-docs issue tracker if something is unclear
