### ISSUE TITLE
Reuse insists on copyright in dep5 thus is incompatible with CC0 licensed images

### ISSUE THREAD

**Issue by MarkCallow** [fsfe/reuse-tool#290]
I have some CC0 licensed images. Anything licensed as CC0 expressly has no copyright. If I omit the Copyright: line from the entry in dep5 then `reuse lint` prints multiple messages about syntax errors in the dep5 file. If I enter an empty copyright, i.e.  `Copyright:`, the syntax error disappears but `reuse lint` reports the file does not have any copyright information and fails.

Note: the error messages are largely useless. The message says there are syntax errors in the dep5 file and is followed by a stack trace of the python code. The stack trace is useless to an end user and the message does not tell you what line number(s) of the file have a syntax error. The identical message and stack trace are repeated multiple times - too many for me to count - and `reuse lint` then proceeds to list every file covered by the dep5 file as not having copyright or licensing information. Extremely user unfriendly. All because of a single missing `Copyright:`.

**Comment by nicorikken** [comment]
I am not a lawyer, but as far as I understand it CC0 is still a license provided by the copyright holder. Copyright cannot be waved, it is automatic and can only be transferred. CC0 is just a license which ensure that in practice the work can be treated as if there is no copyright in place. Some of these issues are addressed in the FAQ. Just look at [the question surround software licensing](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F), there still an author (i.e. copyright holder) is needed.

So in this particular case I think you still need to list a copyright holder.

Even when copyright no longer applies because works have entered the [public domain](https://en.wikisource.org/wiki/Help:Public_domain), Wikimedia for instance still records an original author.

So taking this in consideration I think it is correct for reuse-tool to fail on the lack of copyright information. Even a placeholder value wouldn't work in this case I think.

When it comes to error messages I think there is always room for improvement. Perhaps you can share an output you got?

**Comment by mxmehl** [comment]
CC0 and Public Domain are tricky topics, and largely depend on the applicable legislation. The FAQ tries to explain that a bit [here](https://reuse.software/faq/#uncopyrightable) and [there](https://reuse.software/faq/#exclude-file), but I agree that this might be too little info for many.

Two of my FSFE colleagues are planning to write an article on this topic. I will link it as soon as it's published from the FAQ.

So for the error with the DEP5 file: A copyright line is required by the DEP 5 standard, and for file headers also by REUSE, for the reasons mentioned above. Sorry for not being able to offer more at the moment.

Regarding the unsatifying error, would you please open a new issue with the output, as Nico suggested?
