### ISSUE TITLE
Add support for in-file Markdown declarations as comments

### ISSUE THREAD

**Issue by RogueScholar** [fsfe/reuse-tool#292]
I understand that the variety of Markdown parsers/implementations makes this a tricky ask, but in the interest of more widespread adoption of both the REUSE specification and this tool, I think it's one that should be discussed and implemented sooner rather than later. After a search of not insignificant depth through the family of StackExchange websites on this topic and some hands-on testing of the various suggestions found therein using [Babelmark 2](https://johnmacfarlane.net/babelmark2), my proposal is to use the following syntax ([Babelmark 2 test](https://johnmacfarlane.net/babelmark2/?text=some+text%5Bcomment+text%5D::some+other+text)):

```markdown

[Comment text]::

```

Enclosing the text of comments within square brackets followed by two colons identifies the enclosed text as the label of a [reference link](https://www.markdownguide.org/basic-syntax/#reference-style-links) but breaks its use later in the document if for some unknown reason an attempt was made to use it as such a link, ensuring it has no meaningful impact on the output of any of the 31 parsers tested by Babelmark (including those used by GitHub and GitLab to render Markdown files in hosted repositories), and is tolerant of the use of angle brackets, colons and other characters which are considered "special" when encountered elsewhere. I believe by utilizing this syntax, surrounded by blank lines both above and below and inserted at the top of the document or just below a top-level header (if present), in the same way shebangs are handled for other file types, provides a sufficiently robust mechanism for in-file copyright and licensing declarations such that explicit license files will no longer be necessary for Markdown files in REUSE-compliant projects.

My expectation is that this will reduce resistance to adopt of the specification by reducing the number of added files required to achieve compliance which many developers are sensitive to, especially in the root directory of a project, where Markdown files' presence is often concentrated.

**Comment by nicorikken** [comment]
Maybe I'm missing your point, but in the recent `addheader` commands I've run on codebases, the copyright information was added using the `<!-- ... -->` commenting style. So no `.license` file was created. Could it be that you are trying to address an issue that has already been resolved?

**Comment by Number6174** [comment]
I have a few things to add to this. For a project I am working on that renders Markdown using QT's QML TextEdit box, comments of the form `<!-- ... -->` were not working correctly. The comments were being rendered. After doing some searching, I found solutions similar to the `[comment]::` that has been suggested by @RogueScholar . This worked for rendering, but then the reuse tool did not understand embedded SPDX comments. At the time, I chalked this up to some weird interaction, and just added `.license` files.

After seeing the most recent comment by @nicorikken , I did some more testing.

1. Using addheader, creates a header like:
```
<!--
SPDX-FileCopyrightText: 2021 Number6174
SPDX-License-Identifier: CC0-1.0
-->
```
This fails for me because only the first line containing the `<!--` is treated like a comment during rendering. Some sources I've seen suggest that a third hyphen at the comment opening, ie `<!---` would work, but it does not in my case. It does pass `reuse lint`.

2. Using a comment as suggested by @RogueScholar like:
```
[SPDX-FileCopyrightText: 2021 Number6174] ::
[SPDX-License-Identifier: CC0-1.0] ::
```
Fails for rendering, and fails `reuse lint` with the error:
```
reuse._util - ERROR - Could not parse 'CC0-1.0] ::'
reuse.report - ERROR - Unexpected error occurred while parsing '/.../test.md'
KeyError: 'path'
```

3. Using a comment as suggested on [Stack Overflow](https://stackoverflow.com/a/32190021) like (Note blank lines prior to each comment):
```

[comment]: # (SPDX-FileCopyrightText: 2021 Number6174)

[comment]: # (SPDX-License-Identifier: CC0-1.0)
```
Works for rendering, but fails `reuse lint` with a similar error as option 2:
```
reuse._util - ERROR - Could not parse 'CC0-1.0)'
reuse.report - ERROR - Unexpected error occurred while parsing '/.../test.md'
KeyError: 'path'
```

4. Using HTML style comments one per line like:
```
<!-- SPDX-FileCopyrightText: 2021 Number6174 -->
<!-- SPDX-License-Identifier: CC0-1.0 -->
```
Works for both rendering and for `reuse lint`. It also works just fine with the three hyphen version.

In the source of reuse (`src/reuse/_comment.py`), it treats Markdown as just using an HTML comment:
```
    ".markdown": HtmlCommentStyle,
    ".md": HtmlCommentStyle,
```

Ultimately, I don't know what the right answer is, but I do think there is still something here. I believe that `lint` should support the formats of 2 and 3 since they are forms for Markdown comments recommended when randomly searching around. I also think that treating Markdown as just HTML for `addheader` isn't quite correct, but I'm not sure what the correct answer for it is. Part of this is complicated by the fact there are many Markdown rendering engines and they appear to all treat things like comments in subtly different ways.

In case it is relevant, I'm using reuse 0.12.1 installed via pip inside WSL, and rendering in QT 5.15.2.

**Comment by mxmehl** [comment]
We have to distinguish two cases here:

1. addheader: comment style that the tool uses to add a header to a file
2. lint: how the tool detects headers

In 1., the comment style actually matters, obviously. But for 2., the style doesn't matter at all. The tool looks for typical strings (SPDX-License-Identifier, SPDX-FileCopyrightText, Copyright, ©, ...) and tries to match its value.

The parsing issue `reuse._util - ERROR - Could not parse 'CC0-1.0)'` occurs because there is no SPDX license identifier `CC0-1.0)` (note the bracket). The tools seems to try to evaluate everything after `SPDX-Licence-Identifier: `, so the suffix elements (brackets, colons) cause the error.

I see two potential action points here:

1. Improve the error output in this case to be more human readable and understandable (e.g. "The license `CC0-1.0)` is unknown").
2. See whether _util can be improved to strip the license string from brackets and colons. Could conflict though, and might be problematic in conjunction with valid SPDX license expressions.

For your immediate issues, using the fourth option (separate inline HTML comments) is definitely a viable option. You should be able to create a template for it for your markdown files.

Changing the default markdown comment syntax seems to be a bit risky for me, as long as your markdown files do not have a distinguishably different file extension.

**Comment by Number6174** [comment]
I agree there are two points here, but I have a couple things to add.

As for the `addheader` functionality, I'm not really all that personally concerned. I have a very reasonable option that works for me. Truth be told, I hadn't even used the `addheader` functionality prior to writing my previous comment and likely won't use it as copy/paste from existing working files is just simply easier.

My personal usage of Markdown is infrequent enough that when I need do something non-trivial in it, I always have to look up the proper syntax. Part of the complicating issue is there is not an authoritative Markdown specification. In this case, the ["original" specification](https://daringfireball.net/projects/markdown/syntax) simply doesn't address the concept of a comment at all. It does say "For any markup that is not covered by Markdown’s syntax, you simply use HTML itself." I think this can be read to support the idea that `<!-- -->` is reasonable for comments. However, in practice, apparently many different Markdown interpreters don't always agree, as evidenced by the multitude of answers if you search for say "Markdown comments". Clearly trying to resolve this here is futile, as having an opinion on how people use Markdown is not the point of the reuse tool. Treating Markdown as HTML is probably close enough for `addheader` usage, even if there is plenty of evidence it isn't fully correct.

As for the parsing issue, it is worth noting that even:
```

[comment]: # (SPDX-FileCopyrightText: 2021 Number6174 )

[comment]: # (SPDX-License-Identifier: CC0-1.0 )
```
fails with effectively the same error as before. Note the space prior to the `)` in this case, and the space will also be present in the error. Given that option 4 above works, the parsing code clearly can support closing comment characters on the same line to some extent. It also works in the case of a C-style multi-line comment like:
```
/*SPDX-FileCopyrightText: 2021 Number6174*/
/*SPDX-License-Identifier: CC0-1.0*/
```
Note no space between `1.0` and `*/`. It also works with
```
<!--SPDX-FileCopyrightText: 2021 Number6174-->
<!--SPDX-License-Identifier: CC0-1.0-->
```
which also doesn't have spaces between the text reuse cares about and the open/close comment character. I haven't looked at the relevant code, but I have to imagine it can be extended to support these Markdown style comments as well. 

I don't think simply enhancing the error message in this case is good enough. The reason why is this very simple user story, which is how I stumbled across this issue:

1. Adopt reuse for a project
2. Add a Markdown file to this project. Recognize that it needs licensing information for this file
3. Web search "Markdown comment" and find something like option 3 above
4. Find reuse doesn't support this format of a comment

This user shouldn't have to go through trying lots of variations of comment formats to find which precise combination works for their specific Markdown parser and the reuse tool simultaneously.

**Comment by mxmehl** [comment]
Thanks for elaborating. You are right, there must be some logic how comment characters are stripped from the copyright/license values. We'll have to dig into that and see how this works and how it could be extended without interfering with SPDX license expressions or so.

**Comment by ra-hardy** [comment]
I thought it might be appropriate to use `<meta>`.  I gave it a go:

```
<meta name="copyright" value="SPDX-FileCopyrightText: © 2021 Tech and Software Ltd.">
<meta name="license" value="SPDX-License-Identifier: GPL-2.0-only">
```
For rendering, it works ok with github and VS Code.  Bitbucket shows the <meta> tag, which is probably a bug with their renderer.  However, reuse lint fails:

```
reuse._util - ERROR - Could not parse 'GPL-2.0-only">'
```

I can fudge it buy putting the `">` after the license on the next line, but I suspect that's dodgy syntax.

**Comment by bact** [comment]
[Jekyll](https://jekyllrb.com/docs/front-matter/) and GitHub support YAML metadata at the top of Markdown file like this:

```markdown
---
SPDX-FileCopyrightText: 2025 Authors
SPDX-License-Identifier: CC0-1.0
---

Content
```
