### ISSUE TITLE
LICENSES directory is not a standard location

### ISSUE THREAD

**Issue by marikaner** [fsfe/reuse-tool#299]
Dear reuse maintainers,

I want to be both compliant with the reuse specification, but it expects me to have the license file in the LICENSES directory, which is not a standard location for licenses - usually this is a LICENSE file in the root directory of the project. This leads to two main issues:
1. Typically in projects that are available on GitHub, there is a LICENSE file.
Based on this GitHub determines the licensing information that is consistently displayed throughout all GH projects.
<img width="134" alt="Screenshot 2021-01-14 at 14 01 54" src="https://user-images.githubusercontent.com/868536/104594201-1cd5d100-5671-11eb-99ac-a642b42aedfe.png">
This does not work for our reuse compliant project. 🙁 

2. We want to earn the [CII badge](https://bestpractices.coreinfrastructure.org/en) which is proof that we are following best practices, etc.
However, there is one rule that we are unable to achieve: [The license needs to be found at a standard location](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.license_location).

I know that there are projects out there that might have multiple licenses, but most projects don't - shouldn't reuse accept the standard LICENSE file in the root of a project as well?
Is there a good reason for this to not be allowed? And what is the recommendation here? I would prefer not to duplicate the LICENSE for obvious reasons.

**Comment by nicorikken** [comment]
Personally I think CII and REUSE are compatible. It requires the license to be in '**a** standard location'. `LICENSES/` is much a standard location as `LICENSE` or `LICENSE.md` are. Just by a different standard. REUSE was created based on existing practices, so I assume the `LICENSES/` was already in common use before REUSE. But @mxmehl might know better.

I like the directory approach, as it is better equipped to deal with projects that are licensed in a more complicated matter.

I think the real issue here is that GitHub is only looking for the single files in a repository:
* https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository
* https://github.blog/2015-03-09-open-source-license-usage-on-github-com/

Perhaps REUSE can get in contact with GitHub to have them support a directory-based approach?

**Comment by mxmehl** [comment]
> REUSE was created based on existing practices, so I assume the LICENSES/ was already in common use before REUSE.

Actually, REUSE invented the LICENSES directory for the current 3.0 version, at least we're the first standardised initiative doing that. Before that, we tinkered with modifiying the LICENSE file, or having multiple, differently names LICENSE files, but all was very unclean and unintuitive. The LICENSES directory makes things much easier, for humans and tools alike. Also see https://reuse.software/faq/#single-license

However, nothing stops you from copying a license file to LICENSE or COPYING to have Github and other tools detect it.

> Perhaps REUSE can get in contact with GitHub to have them support a directory-based approach?

Believe, we have been more than once. My last information is that it's on their task list, but no ETA. We're also in exchange with other platforms and tools, and hopefully we'll see proper REUSE support being adopted more widely soon.

**Comment by marikaner** [comment]
Thank you for your quick response @nicorikken and @mxmehl. Than I hope time will fix this ;)

**Comment by marikaner** [comment]
@nicorikken @mxmehl If you are interested: For the CII badge, `LICENSES` will be treated as standard location in the future.
