### ISSUE TITLE
Building reuse-tool from source

### ISSUE THREAD

**Issue by arcturus140** [fsfe/reuse-tool#31]
I need a little heads up on how to build `reuse-tool` from scratch. My Linux distro is using Python 3.5 and I had to upgrade to 3.6 to install dependencies and the application. 

So far I managed to install requirements.txt. 

What are the build steps I have to take?

**Comment by carmenbianca** [comment]
> My Linux distro is using Python 3.5 and I had to upgrade to 3.6 to install dependencies and the application.

This is very, very ill-advised. I don't know what steps you took to do this, but this is potentially OS-breaking. If you need a separate version of Python, either upgrade your distribution (recommended) or use a tool like [pyenv](https://github.com/pyenv/pyenv) to install a local version of Python in your home directory.

Otherwise, the steps are documented in the README:

    git clone git@github.com:fsfe/reuse-tool.git
    cd reuse-tool/
    python3 -mvenv venv
    source venv/bin/activate
    make develop

In the case of using pyenv, you want to make sure that the third step (`python3 -mvenv venv`) instead uses pyenv's version of Python, which is probably something like `~/.pyenv/versions/3.7/bin/python3 -mvenv venv`, but I'm not sure.

**Comment by mxmehl** [comment]
This seems to be resolved. The [Dockerfile](https://github.com/fsfe/reuse-tool/blob/master/Dockerfile) also shows how easy installation from source can be.
