### ISSUE TITLE
How to use reuse-tool on Trisquel and similar without pip

### ISSUE THREAD

**Issue by dancesWithCycles** [fsfe/reuse-tool#348]
Hi folks,
thank you very much for creating and maintaining this repository. I am using it already on a computer with Debian GNU/Linux and fully satisfied with everything working out of the box yet.

Now, I would like to use `reuse-tool` also on my `Trisquel` computer. You maybe know, that the `pip` package is not available on `Trisquel` as it supports/facilitates the installation on nonfree/proprietarty software.

Do you know a workaround how I can use `reuse-tool` on `Trisquel` even without `pip`? I do not see a dedicated package for `Trisquel` or its origin `Ubuntu 18.04`. Or, am I blind?

If I can figure out the dependency list of `reuse-tool` I might get it running even without `pip`. Would you say I can use the dependency graph of GitHib as source for a complete dependency list?

I appreciate any advice that points me in the right direction. Cheers!

**Comment by CharString** [comment]
Unless they patched it out of the standard library that comes with python, the `ensurepip` module can help you install pip. I like installing command line tools like `reuse` with `pipx`. So this should do the trick.

    python3 -m ensurepip
    pip install --user pipx
    pipx install reuse

This will install `reuse` and its dependencies in its own virtualenv in your home directory where it won't interfere with any other python package you might have on your system and put symlinks to the cli tool(s) in ~/.local/bin, the standard xdg location for user executables.
Check the output of pipx for tips on how to keep the packages up to date, as they won't be monitored by your system's package manager `apt`

**Comment by mxmehl** [comment]
Thanks for the info, @CharString.

@dancesWithCycles does this work for you? Unfortunately I am not aware of other methods to achieve your goal.

**Comment by nicorikken** [comment]
@dancesWithCycles Rather than trying to install pip, you could also try to get it working using default OS packages. The required tools can be found in the requirements section of `setup.py`: https://github.com/fsfe/reuse-tool/blob/master/setup.py#L18-L34 which amounts to:
```
python-debian
requests
license-expression
boolean.py
Jinja2
binaryornot
```

In a [preliminary Debian package](https://ftp-master.debian.org/new/reuse_0.12.1-1.html) this was expressed as the following OS dependencies:
```
python3-binaryornot
python3-boolean
python3-debian
python3-jinja2
python3-license-expression
python3-requests
python3:any
```

So hopefully the listed packages are also available on Trisquel. In that case you should just be able to install it from source and run it.

**Comment by mxmehl** [comment]
> In a [preliminary Debian package](https://ftp-master.debian.org/new/reuse_0.12.1-1.html) this was expressed as the following OS dependencies:

`python3-license-expression` is only available in unstable, while `reuse` is [in the NEW queue](https://ftp-master.debian.org/new/reuse_0.12.1-1.html) and waits for a Debian FTP person to be merged. So hopefully we'll see an official Debian package soon, but probably only after the release of Debian 11.

**Comment by dancesWithCycles** [comment]
Hi @CharString ,
Thank you very much for pointing me in that direction. I am running Trisquel 9, which is supposed to be related with Ubuntu 18.04, with the following details.

```
uname -a
Linux frieda 4.15.0-140-generic #144+9.0trisquel7 SMP Thu Mar 25 02:57:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

When I call your suggestion, I receive the following feedback.

```
python3 -m ensurepip
/usr/bin/python3: No module named ensurepip
```

Does someone has an explanation for this feedback. Is there something missing that I can install with ```apt``` avoiding ```pip```?

Hi @nicorikken ,
Thank you very much for the hint installing ```reuse``` dependencies using OS default packages. From the list you provided above all packages are available but the following.

```
python3-boolean
python3-license-expression
```

At the end of the day, I am still unable to use ```reuse``` on Trisquel 9 at the moment. I hope this is changing with future default OS packages for Debian or Ubuntu.

Anyhow, please accept my appreciation for your help!

**Comment by CharString** [comment]
@dancesWithCycles Maybe explain to the maintainers of your distro that they are making it difficult for you to use free software? The irony is that you are trying to use an fsf package that just happens to be written in python.

They quote RMS in [their decision to remove language package managers](https://trisquel.info/en/issues/20439#comment-form), because you might be unknowingly installing non-free software. But from the RMS email:

> Since there are so many different problem repositories, I think we can't
try to deal with them all at once.  We should look for volunteers to make
replacement repositories for a couple of them, based on automatic
filtering not manual vetting.

The Python Packages Index (pypi) contains meta-data about the licenses of packages. Instead of blocking you from using it, because there's a minority of non-free software in there (most of it is MIT or BSD licensed) they could setup a mirror or proxy that only provides the free packages, based upon that metadata.

I tried registering and making the point there myself, but ended up in a manual queue for admittance. And I've lost aplomb and interest. That said you can always install from source. Just clone the repository and run `python setup.py install` there. Better yet, run that as root, so it installs it system wide. And then tell the Trisquel people `pip install --user` could have prevented you from borking your system.

I applaud their cause of free software, but their blocking of pip is misguided. Free software is like unbleached recycled toiletpaper. They are blocking you from getting it in the store in your town, because that store also has the 4 ply plush bleached stuff made from corporate pulp. But instead of opening shop along side it, or give you a shopping basket that warns you when you put in the plush stuff, they tell you to roll your own, or ask the manufacturers of the recycled stuff to support you.

**Comment by dancesWithCycles** [comment]
Hi @CharString ,
Thank you very much for clarification. I agree with you and very much like the toilet paper analogy. You motivated me to make the point myself at Trisquel. We will see if I end up in the same way as you are.

Cheers!

**Comment by mxmehl** [comment]
Good luck with convincing the Trisquel people. I hope they will understand the reasoning.

> The irony is that you are trying to use an fsf package that just happens to be written in python.

Just to clarify: REUSE is a tool maintained by the FSFE, an independent organisation. However, as you can see, it's fully Free Software.

I'll close this issue because we probably won't patch around pip anytime soon. However, feel free to use this thread to share experiences and track the progress with such distros.
