### ISSUE TITLE
Teach `reuse addheader` about adding comments to XML files

### ISSUE THREAD

**Issue by rpavlik** [fsfe/reuse-tool#383]
The existing styles mostly work for projects  I've used them on, with the exception of any XML files (which include msbuild files, manifests for various platforms, etc.). I tend to just put a big comment after the opening element (or the `<?xml` element if it's there).

This is also how I add copyright headers to markdown files.

**Comment by mxmehl** [comment]
We've had the issue that `addheader` added the header before the `<?xml` element which broke the file. That has recently been fixed with #378 and will be present in the next release. A similar approach is there for shebangs.

For all the rest, it adds comments at the top.

I hope that will fix your issue?

**Comment by rpavlik** [comment]
It has a comment style for XML files?

Ohhh, I bet it's the one named HTML. Totally didn't think to look for HTML in the list when I wanted XML.

**Comment by mxmehl** [comment]
Yes, exactly. The style names are a bit confusing (Python for `#` is also used in many other languages). See it as a historically originated peculiarity ;)
