### ISSUE TITLE
Files ignored by git are not ignored by reuse

### ISSUE THREAD

**Issue by SanderTheDragon** [fsfe/reuse-tool#385]
I was trying out this tool, and it is good, but I noted that it lints files which should be ignored.

The following commands can be executed to reproduce the issue:
```
mkdir gitignoretest
cd gitignoretest
git init
curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/python > .gitignore
mkdir src
cd src
echo "print('hi')" > hi.py
echo "import hi" > main.py
python3 main.py
reuse lint
```

This will show the expected `../.gitignore`, `../src/hi.py` and `../src/main.py`, but it also includes `../src/__pycache__/hi.cpython-39.pyc` (could have a different name).
Running `git status -u` does not show `__pycache__/hi.cpython-39.pyc` so it is ignored correctly.

Moving the contents from `src` to the main directory fixes it (so it could be also something with `git ls-files`).
Removing the `--directory` flag from [vcs.py](https://github.com/fsfe/reuse-tool/blob/master/src/reuse/vcs.py#L88) also seems to fix it.

**Comment by mxmehl** [comment]
I was able to reproduce your error. The problem seems to be in the `git ls-files` command. Since `__pycache__/`'s parent directory `src` is unknown to git in your example, it does not seem to take the ignored file into consideration.

If you run `git add src/main.py`, `reuse lint` does not consider the pycache any more.

`--directory` is there for a reason: for performance reasons, we just want to ignore the whole directory, not all of the files it contains.

**Comment by SanderTheDragon** [comment]
That makes sense, so I will just ignore it while developing, since it will dissapear when I add it to git. Maybe a note in the FAQ could be useful for other people (even though this issue probably does not occur often).

**Comment by ForNeVeR** [comment]
JFYI, this is still quite confusing and messes up with my local workflow when I try to add a directory with a bunch of nested ignored files, and check the linter rules before that.
