### ISSUE TITLE
Provide a means of participating in this standard which does not require nonfree software

### ISSUE THREAD

**Issue by ddevault** [fsfe/reuse-tool#443]
I have feedback to share but I will not share it on GitHub.

**Comment by mxmehl** [comment]
No problem, please find other contact channels on our website: https://reuse.software/resources/#contact

If you'd have pull requests, you can also send me patches via email. My contact details are linked on the aforementioned page.

**Comment by ddevault** [comment]
Thanks, I will use those resources. I will state for the record, however, that hosting an official FSFE project on a nonfree software forge is -- pardon my language -- utter horseshit.

**Comment by seabass-labrax** [comment]
There's been some development in Gitea (not yet merged) to add suffixes to usernames that come from OAuth providers. This would allow the FSFE Git repository to allow logins with either an FSFE account or an external OAuth provider. https://github.com/go-gitea/gitea/issues/7014

I remember @mxmehl saying (correct me if I'm wrong) that this would be a requirement for the REUSE tool to be hosted on [git.fsfe.org](https://git.fsfe.org), as most of the contributors don't have accounts there.

**Comment by aschrijver** [comment]
Since both Gitea and Codeberg are mentioned here, I'd like to update here the recent developments where Codeberg is now running on top of (the soft fork) [Forgejo](https://forgejo.org) which has been created as [result of the incorporation](https://gitea-open-letter.coding.social) of Gitea Ltd.

FWIW I will bring attention to @seabass-labrax [comment](https://github.com/fsfe/reuse-tool/issues/443#issuecomment-998862285) above to the [Forgejo matrix chatroom](https://matrix.to/#/#forgejo-chat:matrix.org) where I am active. Codeberg/Forgejo are fully dedicated to Free Software and might be interested to consider bringing these changes, esp. if that helps move FSFE REUSE to Free Software again as well.

**Comment by mxmehl** [comment]
I can only speak for myself but I am excited about the recent work done to make Gitea/Forgejo federate. As mentioned numerous times already in different discussions, a working federation would most likely enable the REUSE tool to finally switch to a fully Free Software development platform without losing too many contributors.
