### ISSUE TITLE
No way to open issues for some repos

### ISSUE THREAD

**Issue by hoijui** [fsfe/reuse-tool#549]
This is probably intentional, but just in case it is not:
Many of the repos under this github account are mirrors of https://git.fsfe.org repos, and as such they have issues turned off (makes sense). As much as I have seen, it is not possible for everyone to create an account on https://git.fsfe.org, and thus we can not create issues there. I see a rationale for that, and do not want to argue against it. I just want to say that I would now have made an issue there.

## Why do I want access?

I am writing a tool that is in spirit very similar to the REUSE tool. it is also CLI only, takes Open Source (Hardware) git repos as input, analyzes them, and gives a general fitness report in form of plain-text as output.
We would like to reuse the REUSE API and API-workers to host our own service for badges and reports. I am just starting with this part of the project, but I am not a natural to docker and hosting and services and web and all that, and I sure will run into problems and have questions, and I think I will at some point want to contribute a bash script that doe everything to setup a test environment (download API and API-worker repos, install deps, build, configure, run, run test-requests).

## Example repos

- https://github.com/fsfe/reuse-api
- https://github.com/fsfe/reuse-api-worker
- https://github.com/fsfe/forms

**Comment by linozen** [comment]
Hi @hoijui and thanks for your interest im REUSE.

We really like our Gitea instances but are also painfully aware of some of its (current) limitations. You mentioned perhaps the most important one. Until we have figured out something (e.g. federation), may I suggest you address your specific questions regarding the API to the mailing list: https://lists.fsfe.org/mailman/listinfo/reuse? If you uncover a bug, I'll make sure it ends up in our issue tracker over on https://git.fsfe.org

**Comment by hoijui** [comment]
ok.
Though, I would strongly recommend against waiting for federation to solve this. That is simply too unrealistic/too far in the future going to be practically usable, both in gitea and in general. I say that, being aware of their plans, and having great need for it to happen too.
Thanks for the mailing-list option! :-)

**Comment by Ryuno-Ki** [comment]
> Though, I would strongly recommend against waiting for federation to solve this.

I second this (I'm contributing to Gitea since a few weeks). Looking at [State of the Forge Federation report](https://forgefriends.org/blog/2022/06/30/2022-06-state-forge-federation/) the first federation bits are expected to arrive within a year.

If you can channel some Go developers our way, help is appreciated :)

REUSE is [on the radar](https://discuss.coding.social/t/licensing-reuse-conformance/87) of a related movement.

I'm stopping issue hijacking here.

**Comment by hoijui** [comment]
@Ryuno-Ki Do I get it right, that no work *in* gitea regarding this has been done yet, but only in tools/libs you will later use in gitea?
and either way, the part in gitea . will it be developped in the open in the main gitea repo?

**Comment by Ryuno-Ki** [comment]
> @Ryuno-Ki Do I get it right, that no work _in_ gitea regarding this has been done yet

Correct. It's on the roadmap, but not available yet.

> but only in tools/libs you will later use in gitea?

Can't answer this, since I am more involved with the Frontend.

> and either way, the part in gitea . will it be developped in the open in the main gitea repo?

Yes, it's going to be developed in the open. I'm not :100: sure about the main gitea repo. It will end up there, but from my observation, some developers host their own Gitea instance where they upload their work first.
