### ISSUE TITLE
feature request: add support for contributors to addHeader

### ISSUE THREAD

**Issue by sgaist** [fsfe/reuse-tool#615]
This issue is a follow up of the discussion started in #612.

The idea is to add support for the `SPDX-FileContributor` field to the addHeader command so that one can set the copyright to an entity while still give credit to the authors of the file.

An example call I had in mind is:
```
reuse addheader --copyright="Example Labs ltd" --license=MIT --contributor="Charly Doe" --contributor="Jordan Doe" my_file.py
```

The result could look like the following:
```
# SPDX-FileCopyrightText: 2019 Example Labs ltd
#
# SPDX-FileContributor: Charly Doe
# SPDX-FileContributor: Jordan Doe
#
# SPDX-License-Identifier: MIT
```

_Originally posted by @sgaist in https://github.com/fsfe/reuse-tool/issues/612#issuecomment-1277791425_

**Comment by nicorikken** [comment]
Great idea. Link to the current documentation of this field: https://spdx.github.io/spdx-spec/v2.3/file-information/#8.14 I think many projects won't adopt this because it would add even more lines to the header. Still, it would be great to have it available for those who want to use it. I think it fits the scope of reuse-tool.

**Comment by mxmehl** [comment]
Would be fine with me, as this would allow to add oneself to the file even if the copyright is e.g. the project's or company's.

I already foresee the request to get this information from the VCS or a personal defaults file though.
