### ISSUE TITLE
Lisp comment character should go back to using double semicolons

### ISSUE THREAD

**Issue by wasamasa** [fsfe/reuse-tool#637]
I've noticed that reuse reverted from using two semicolons to just one, with no explanation for the rationale: https://github.com/fsfe/reuse-tool/commit/caa802a52ff45add6175cf23b8db0951fb9c3a54

In Lisp dialects, it's common to use different numbers of semicolons depending on the meaning of the comment:

```elisp
;;;; top-level comment

;;; heading comment

(defun test ()
  ;; line comment
  (+ 1 1)) ; inline comment
```

Therefore, using just one semicolon is incorrect since it's for inline, not line comments. Two semicolons is fine for me. Some people would argue four semicolons is appropriate since the copyright line and SPDX identifier are at the top-level of the file. If you want to, I can dig up examples of use in the wild.

References:

- Emacs Lisp: https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html
- Scheme: https://mumble.net/~campbell/scheme/style.txt
- Common Lisp: https://lisp-lang.org/style-guide/#comment-hierarchy
- Clojure: https://guide.clojure.style/#comments

**Comment by carmenbianca** [comment]
I think I recall. It's because `addheader` (now `annotate`) replaces the first comment section it can find. But if the comment character is `;;`, it won't recognise a comment field using just `;` as a comment field.

So if you run `reuse annotate --license MIT filename` on this file:

```
; Copyright Me
; SPDX-License-Identifier: 0BSD
```

You get this:

```
;; SPDX-License-Identifier: MIT

; Copyright Me
; SPDX-License-Identifier: 0BSD
```

But I'm not 100% sure. In any case, weird things lie this way. I think it's possible to fix this, but it won't be super trivial.
