### ISSUE TITLE
License not found in YML files?

### ISSUE THREAD

**Issue by lvca** [fsfe/reuse-tool#681]
I can't get my compliance back on ArcadeDB project:

https://api.reuse.software/info/github.com/ArcadeData/arcadedb

The issue seems to be with this file, but as you can see, there is the Apache license header on it:

https://github.com/ArcadeData/arcadedb/blob/9d4deef11bd639b008a10c5a7312605b0a47aef0/docker-compose.yml

Any idea?

**Comment by seabass-labrax** [comment]
Hello @lvca! This is an intentional part of the REUSE specification; each file must have an [SPDX License Identifier](https://spdx.org/licenses/) in the comment header. This can be either instead of or in addition to the licence's usual header, like the Apache 2.0 one in your source file. Here's the particular section of the REUSE specification that covers this: <https://reuse.software/spec/#comment-headers>.

The reason for this is that SPDX License Identifiers make it easier for software, like the REUSE tool, to automatically scan packages for licensing information. Many licences don't have a recommended comment header, making REUSE extra useful in these cases.

I'm not one of the maintainers of REUSE, but I am on SPDX's Steering Committee, so please let me know if you have any questions about this :smiley:

**Comment by lvca** [comment]
That's right, the SPDX identifier. I just added it and it works. Thanks for the quick answer.
