### ISSUE TITLE
New REUSE badge has not refreshed yet

### ISSUE THREAD

**Issue by dominiksalvet** [fsfe/reuse-tool#76]
Hello! I am a big fan of the new REUSE badge as it is simpler and smaller. However, it seems that GitHub caches some images on their servers and unfortunately includes the REUSE badge in this caching process. The following image should illustrate the new REUSE badge (from the [official REUSE website](https://reuse.software/dev/)) but in reality it is the older one:

[![reuse compliant](https://reuse.software/badge/reuse-compliant.svg)](https://reuse.software)

So right now I am stuck with the older REUSE badge wherever I go on GitHub. I suspect that it is not only my problem and it affects more users. Please, let me know whether you are affected as well.

Do you know if there is any refresh interval of their cached images by chance? If so, what is the interval? Is there anything to do to get the new REUSE badge working?

If I can be of any help, feel free to ask.

**Comment by carmenbianca** [comment]
@mxmehl should be able to dig into this. It's not worth putting much time into, however, because we'll be adding a small service for badges soon. e.g., you request the badge at https://reuse.software/badge/?url=$my_url_here, and you get a green or red badge depending on whether the project is actually compliant. It's still in the works, however.

**Comment by mxmehl** [comment]
This should be fixed now, I've disabled caching for SVG files basically. Thanks for reporting!

https://github.com/fsfe/reuse-website/commit/c75e61b435d297d5d2a12e938ee585631218332a

The live badge service is almost finished, we will release it soon :)
