### ISSUE TITLE
Specifying files to ignore

### ISSUE THREAD

**Issue by WhyNotHugo** [fsfe/reuse-tool#796]
`reuse lint` is checking a lot of file that aren't code and complaining that they're missing licence headers.

Is there some way that I can tell `reuse` to ignore these files (e.g.: something like `.gitignore`)?

Most of these are configuration files (e.g.: port number, username, password), lockfiles or files that are a list of dependencies.

**Comment by carmenbianca** [comment]
[This is not possible](https://reuse.software/faq/#exclude-file).

You have to specify a way that you want to deal with these files. You can look at this repository's `.license` files and `.reuse/dep5` file for inspiration.

**Comment by WhyNotHugo** [comment]
As far as I understand, these files are not something for which copyright is applicable.

For example, one contains a port, a username and a password.

Another contains the hashes of dependencies (and it is machine generated, so am I even the author of it?).

**Comment by carmenbianca** [comment]
The [threshold of copyrightability](https://en.wikipedia.org/wiki/Threshold_of_originality) is very poorly defined. So [our advice](https://reuse.software/faq/#uncopyrightable) is to just slap a copyright notice anyway.

The goal is to provide copyright and licensing information for _all_ relevant files. If we provide an exception for uncopyrightable files (which would be nice), we would have to define the threshold of originality in code and in spec in REUSE (which would not be nice, and which would make a lot of lawyers and legal experts very angry at us).

Claiming copyright over uncopyrightable stuff, however, is unlikely to upset the lawyers, because they'll just laugh at you a little and do with the uncopyrightable file as they like.

Alternatively, we could implement a method to tag a file as 'uncopyrightable', but if you do this and the recipient disagrees that the file was uncopyrightable, then the recipient now has no licence to use that file.

**Comment by WhyNotHugo** [comment]
> Claiming copyright over uncopyrightable stuff, however, is unlikely to upset the lawyers, because they'll just laugh at you a little and do with the uncopyrightable file as they like.

True, this sounds pretty safe.

> Alternatively, we could implement a method to tag a file as 'uncopyrightable', but if you do this and the recipient disagrees that the file was uncopyrightable, then the recipient now has no licence to use that file.

Yeah, I guess that can open to door to all kind of issues, given that someone might say "Oh, my `header.h` file is not copyrighteable.
