### ISSUE TITLE
Duplicate SPDX-License-Identifier line if switching licenses

### ISSUE THREAD

**Issue by klmcadams** [fsfe/reuse-tool#844]
Hi, I noticed there's a duplicate SPDX-License-Identifier line in the header if you change from one license type to another when running `reuse annotate`, so I was wondering if that's expected? I'm using reuse v2.1.0 on Python 3.10.5, and attached a zip containing .reuse/templates, LICENSES, and existing_header.py if you want to run the commands below with the same templates.

For example, when I run `reuse annotate --year 2023 --copyright-style "string-c" --copyright "my copyright" --template mit --license MIT --skip-unrecognised --merge-copyrights existing_header.py`, it has one SPDX-License-Identifier line:

```
# Copyright (C) 2023 my copyright
# SPDX-License-Identifier: MIT
```

Assuming existing_header.py has the MIT license and we want to change it to ECL-1.0, then I would run `reuse annotate --year 2023 --copyright-style "string-c" --copyright "my copyright" --template ecl-1.0 --license ECL-1.0 --skip-unrecognised --merge-copyrights existing_header.py`, which creates two SPDX-License-Identifier lines:

```
# Copyright (C) 2023 my copyright
# SPDX-License-Identifier: ECL-1.0
# SPDX-License-Identifier: MIT
```

If I comment out this line in header.py, it doesn't make the duplicate SPDX line when I switch from the MIT license header to the ECL-1.0 header: https://github.com/fsfe/reuse-tool/blob/9e1d3793651c8a76618a5d804384edd4c94fb180/src/reuse/header.py#L187

Thank you for your time!

[reuse_example.zip](https://github.com/fsfe/reuse-tool/files/13032887/reuse_example.zip)

**Comment by mxmehl** [comment]
Indeed, that's how it works, and it makes sense, somehow. You apply license and copyright information to a file, and if there already is information, the tool does not just overwrite it but extend it. I believe the original intention was that the tool shall not delete existing copyright/licensing information.

Two SPDX-License-Identifier lines are possible although not recommended. They basically can be translated into the expression `SPDX-License-Identifier: ECL-1.0 AND MIT`.

REUSE currently doesn't have the feature to explicitly overwrite existing licensing/copyright information. If you were to change a license, I'd rather recommend using `sed` or a similar tool.

A side note: In order to "add" information via REUSE, you don't need to re-run the whole `reuse annotate` command. E.g. if you only want to add a copyright holder, `reuse annotate -c "Jane Doe" $files` suffices. It won't delete old information as we've learnt.

**Comment by carmenbianca** [comment]
Great explanation by @mxmehl

Maybe it might make sense to have an `--overwrite` flag? À la 'yes I know what I'm doing please remove all old REUSE info from the file'. But it wouldn't be very granular.

**Comment by mxmehl** [comment]
> Maybe it might make sense to have an `--overwrite` flag? À la 'yes I know what I'm doing please remove all old REUSE info from the file'. But it wouldn't be very granular.

It *could* make sense, but I sense that there might be a few edge cases which would require quite some logic. I think it's easier to solve these tasks with other tools like sed or search/replace in IDEs.
