### ISSUE TITLE
This tool has an identity crisis

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#91]
This popped up in #90.

The tool currently goes by the following names:

- reuse --- Its name in the codebase and on the CLI, and on Docker
- fsfe-reuse --- Its name on PyPI because reuse was taken #75 
- reuse-tool --- Its name on GitHub, which is never(?) used anywhere else
- REUSE helper tool --- Its name on the REUSE website

If this could somehow be shrunk down to one name, that would be fantastic. But I'm not sure it can be shrunk down to one. Its name should remain `reuse` on the CLI, barring a better alternative. But `reuse` is not a very good name outside of the context of the CLI.

**Comment by kirelagin** [comment]
`reuse-tool` is as good (bad) as `reuse`. Personally I think `fsfe-reuse` is the way to go.

**Comment by amerlyq** [comment]
Considering distribution packaging practices:
* `reuse` is too generic to be identified as package
* `reuse-tool` suggest existence of something else in `reuse` context which is not tool, but... maybe language, interpreter? Is it even planned? Will it be still `tool` and not `spdx-processor`? :)
* `fsfe-reuse` adds unnecessary attribution to issuer `fsfe` namespace which has no useful meaning in the context of the OSS tool -- it's like `opensuse-snapper` or `google-perftools` which its favorite "All rights reserved." shenigans despite permissive terms.

My suggestion if we go in purpose-context way and expect future extension of tools suite and standards covered by REUSE -- then `reuse-spdx`.
If it's solely dedicated to SPDX -- then `spdx-reuse` will do.

**Comment by davidak** [comment]
>reuse is too generic to be identified as package

There is actually no other package with that exact name.

https://repology.org/projects/?search=reuse&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

But you find some repos on github with the same name.

https://github.com/diegohaz/reuse

I think this is the best name since it is also the command. It's also already packaged with that name even your repo and website uses a different name...

reuse-tool suggest existence of something else in reuse context which is not tool, but... a code licensing initiative? ;)

**Comment by carmenbianca** [comment]
`fsfe-reuse` has been deprecated, which helps the identity crisis by a lot. Closing this because we've decided that the situation is good enough now.
