### ISSUE TITLE
lint fails when called outside of project repo

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#94]
When running reuse lint not inside the repository but at least one level above, reuse lint does complain about missing files in LICENSES/, although they are in the given directory,

Situation:
```
/home/max/
|─ reuse-example
|─ some_other_dir
```

When running `reuse lint` inside of `/home/max/reuse-example`, everything is fine.

When running `reuse lint reuse-example` inside of `/home/max`, it fails. The same if I run `reuse lint ../reuse-example` when running it inside the `some_other_dir`:

```
# MISSING LICENSES

'CC-BY-4.0' found in:
* reuse-example/img/cat.jpg

'CC0-1.0' found in:
* reuse-example/.gitignore

'GPL-3.0-or-later' found in:
* reuse-example/Makefile
* reuse-example/README.md
* reuse-example/img/dog.jpg
* reuse-example/src/main.c


# SUMMARY

* Bad licenses:
* Missing licenses: CC-BY-4.0, CC0-1.0, GPL-3.0-or-later
* Unused licenses:
* Used licenses:
* Read errors: 0
* Files with copyright information: 6 / 6
* Files with license information: 6 / 6
```

Not sure how a good solution could look like since I assume that it is not trivial for the tool to detect what's the root of the project, especially when submodules are included.

**Comment by carmenbianca** [comment]
Found the problem in `create_project`. It always assumes that the root of the project is the current working directory, *or* possibly a parent of the CWD if inside a Git project.

I can easily fix this for the singular `reuse lint example` (simply set the project root to `example`), but I *can't* fix this for the plural `reuse lint example1 example2`.

**Comment by carmenbianca** [comment]
@sschuberth I'm not sure that's entirely applicable. It could be a little bit, but not entirely?

Basically, the problem is this: In order to be able to lint, the tool needs to have some idea of what the root directory of the project is. It currently detects the root directory by checking if the *current working directory* (CWD) is inside of a Git repository. If it is, then it's trivially easy to do some Git magic to figure out the root of the Git repo.

If the CWD is not in a Git repository, then the CWD is assumed to be the root directory. This is a naïve assumption, but kind of works. It's why you can call `reuse lint` without arguments.

But it's a bit of a problem if you're not dealing with a Git repo, and/or can't change your CWD. Which is why `rev-parse` probably isn't going to help.

Maybe a better solution is to do something like `reuse --root=/path/to/example /path/to/example`? It's a bit verbose, but it should do the trick.

**Comment by carmenbianca** [comment]
> > Maybe a better solution is to do something like reuse `--root=/path/to/example /path/to/example`?
> 
> I'm not getting the double `/path/to/example` here, are these supposed to be different examples for different project root, which of which would be linted separately?

I talked with Florian Snow (can't find his GitHub account) about this issue yesterday. There was some confusion between us about what `reuse lint` does. It has some weird behaviour that only makes sense when you understand the history:

When I started working on this tool, I wanted to test it quickly. So I added the following functionality: `reuse lint example.py`. It would take a single file as argument, and lint that single file. This was great for getting started, but that behaviour stuck around.

With the current iteration of this tool, it probably doesn't make sense to lint a single file. It probably also doesn't make sense to only lint a certain directory in a project. e.g., you *could* do `reuse lint src`, and it would only check the files inside of that directory, while preserving the current directory as root. I am not sure what the value of that is, however.

What probably makes most sense is that the tool only accepts project directories. i.e., the path after `reuse lint` **must** be a project directory. `reuse lint reuse-tool` is fine, but `reuse lint src` is not. If that is the case, then `reuse lint` should only accept a single path as argument, rather than multiple paths.

This gets a little tricky, though, because the `--root` argument is actually pretty nifty for some of the other commands. `reuse --root=example download 0BSD`, for instance. With the above suggestion, `reuse --root=example lint` and `reuse lint example` become *functionally identical*, which is a bit confusing. It gets especially confusing when you do something stupid like `reuse --root=example1 lint example2`. Moreover, I would have to fight `argparse` to get any of that to work cleanly.

Sooooo… Not sure what the best path forward is. The current `reuse lint` behaviour is a little weird and should probably be changed. Maybe it makes sense to disallow positional arguments for `reuse lint`? i.e., `reuse lint` and `reuse --root=example lint` become the only valid ways to call the linter.

**Comment by carmenbianca** [comment]
@floriansnow Referenced you in previous comment.

**Comment by mxmehl** [comment]
> Maybe it makes sense to disallow positional arguments for reuse lint? i.e., reuse lint and reuse --root=example lint become the only valid ways to call the linter.

That does make sense to me, thanks for the analysis!

I agree that checking subdirectories does not make much sense in the REUSE mindset. But I accept that it might make sense to have a directory-based overview of REUSE compliance. So instead of allowing linting a single subdir, I would rather extend the lint command with an optional flag to show a tree-like overview of directories and their compliance status.
